
= AppImage for Ipe
:toc: preamble

Here you will find http://appimage.org/[AppImages] for http://ipe.otfried.org/[Ipe].
Please let me know if you have any problems with running Ipe using the AppImages offered on this site: thomas.leitz@web.de.

== Download

You can download the AppImage here or go to https://github.com/unruhschuh/Ipe.AppImage/releases[Releases].

* Download https://github.com/unruhschuh/Ipe.AppImage/releases/download/v7.2.2/Ipe-7.2.2.AppImage[Ipe-7.2.2.AppImage]
* Make the AppImage executable, e.g. in the terminal run `chmod a+x Ipe-7.2.2.AppImage`

== How to create an AppImage for Ipe

The AppImage for Ipe is created inside a fresh installation of CentOS 6.7. In order to build the AppImage follow these steps

* Install CentOS 6.7 either on a PC or inside VirtualBox or any other virtualization program. Using 'testappimage' of AppImageKit also works, but there are issues with dbus.
* Start the Terminal and run `git clone https://github.com/unruhschuh/Ipe.AppImage`
* Change directory with `cd Ipe.AppImage`
* Start compilation and packaging process with `./recipe.sh`. This creates `Ipe.AppImage` inside the current directory.

== Known issues

* The command line tools like `ipetoipe` won't work this way. There would have to be an AppImage for each of the tools. Maybe in a future release. Another approach would be to use `startipe.sh` to allow parameters to start these tools.

